# .github/workflows/metrics.yml
name: Build and Deploy Metrics

on:
  # Runs every 24 hours
  schedule:
    - cron: '0 0 * * *'
  # Allows manual run from the Actions tab
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: anuraghazra/github-readme-stats@v2.0.1
        with:
          # Your GitHub token is necessary to fetch private data.
          token: ${{ secrets.GITHUB_TOKEN }}
          # The Metrics that will be generated:
          plugin_is_generating: yes
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi
          # Add any other metrics here if needed

      - uses: actions/checkout@v4
      - uses: lowlighter/metrics@latest
        with:
          # This creates the image file and commits it to your repository.
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: myselftaimoor
          template: classic
          config_timezone: Asia/Karachi
          repositories_forks: no
          base: header, activity, community, repositories, metadata
          # Use the 'dracula' theme for a clean dark background
          config_palette: dracula